any:
    - 'binary/**'
    - 'jvm-jersey/**'
    - 'php7/**'  
    - 'dotnet/**'
    - 'dotnet20/**'     
    - 'go/**'     
    - 'jvm/**'     
    - 'nodejs/**'
    - 'perl/**'
    - 'python/**'
    - 'ruby/**'
    - 'tensorflow-serving/**'

binary:
    - 'binary/**'
jvm-jersey:
    - 'jvm-jersey/**'
php7: 
    - 'php7/**'  
dotnet:
    - 'dotnet/**'     
dotnet20:
    - 'dotnet20/**'     
go:   
    - 'go/**'     
jvm:  
    - 'jvm/**'     
nodejs:
    - 'nodejs/**'
perl: 
    - 'perl/**'
python:
    - 'python/**'
ruby: 
    - 'ruby/**'
tensorflow-serving:
    - 'tensorflow-serving/**'
