pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - label=ready-to-merge
      - label!=hold-off-merging
      - check-success=check
      - or:
        - check-success=binary
        - check-success=go
        - check-success=jvm
        - check-success=nodejs
        - check-success=perl
        - check-success=php7
        - check-success=python
        - check-success=ruby
        - check-success=tensorflow
    actions:
      merge:
        method: squash
