apiVersion: skaffold/v2beta24
kind: Config
deploy:
  helm:
    releases:
    - name: fission
      remoteChart: https://github.com/fission/fission-charts/releases/download/fission-all-v1.20.3/fission-all-v1.20.3.tgz
      namespace: fission
      setValues:
        analytics: "false"
        canaryDeployment.enabled: "false"
        influxdb.enabled: "false"
        nats.enabled: "false"
        prometheus.enabled: "false"
        routerServiceType: NodePort
      wait: true
    flags:
      install:
      - --create-namespace
      - --timeout=3m
      - --debug
      - --dependency-update
      upgrade:
      - --timeout=3m
      - --install
      - --force
      - --debug
profiles:
- name: dotnet
  build:
    artifacts:
    - image: dotnet-env
      context: dotnet/
      docker:
        dockerfile: Dockerfile
- name: dotnet20
  build:
    artifacts:
    - image: dotnet20-env
      context: dotnet20/
      docker:
        dockerfile: Dockerfile
- name: go
  build:
    artifacts:
    - image: go-env
      context: go/
      docker:
        dockerfile: Dockerfile-1.1x
        buildArgs:
          GO_VERSION: "1.22"
          UBUNTU_VERSION: "22.04"
    - image: go-builder
      context: go/builder/
      docker:
        dockerfile: Dockerfile-1.1x
        buildArgs:
          GO_VERSION: "1.22"
- name: jvm
  build:
    artifacts:
    - image: jvm-env
      context: jvm/
      docker:
        dockerfile: Dockerfile
    - image: jvm-builder
      context: jvm/builder/
      docker:
        dockerfile: Dockerfile
- name: jvm-jersey
  build:
    artifacts:
    - image: jvm-jersey-env
      context: jvm-jersey/
      docker:
        dockerfile: Dockerfile
- name: nodejs
  build:
    artifacts:
    - image: node-env
      context: nodejs/
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NODE_BASE_IMG: "20.16.0-alpine3.20"
    - image: node-builder
      context: nodejs/builder/
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NODE_BASE_IMG: "20.16.0-alpine3.20"
- name: perl
  build:
    artifacts:
    - image: perl-env
      context: perl/
      docker:
        dockerfile: Dockerfile
- name: php7
  build:
    artifacts:
    - image: php7-env
      context: php7/
      docker:
        dockerfile: Dockerfile
- name: python
  build:
    artifacts:
    - image: python-env
      context: python/
      docker:
        dockerfile: Dockerfile
        buildArgs:
          PY_BASE_IMG: "3.11-alpine"
    - image: python-builder
      context: python/builder/
      docker:
        dockerfile: Dockerfile
        buildArgs:
          PY_BASE_IMG: "3.11-alpine"  
- name: python-fastapi
  build:
    artifacts:
      - image: python-fastapi-env
        context: python-fastapi/
        docker:
          dockerfile: Dockerfile
      - image: python-fastapi-builder
        context: python-fastapi/builder/
        docker:
          dockerfile: Dockerfile
          buildArgs:
            PY_BASE_IMG: "3.11-alpine"
- name: ruby
  build:
    artifacts:
    - image: ruby-env
      context: ruby/
      docker:
        dockerfile: Dockerfile
- name: tensorflow-serving
  build:
    artifacts:
    - image: tensorflow-serving-env
      context: tensorflow-serving/
      docker:
        dockerfile: Dockerfile
- name: binary
  build:
    artifacts:
    - image: binary-env
      context: binary/
      docker:
        dockerfile: Dockerfile
        buildArgs:
          GO_BASE_IMAGE: "1.22-alpine"
          ALPINE_VERSION: "3.20"
    - image: binary-builder
      context: binary/builder/
      docker:
        dockerfile: Dockerfile

