#!/bin/sh
set -euxo pipefail

if [ -f ${SRC_PKG}/Gemfile.lock ]
then
	cd $SRC_PKG
	# --deployment is deprecated in bundler 2.x; the config form is equivalent.
	bundle config set --local deployment true
	bundle install
fi
cp -r ${SRC_PKG} ${DEPLOY_PKG}