FROM golang:1.13.15-buster

RUN apt update && apt install -y ca-certificates && rm -rf /var/lib/apt/lists/*
ENV GOPATH /usr
ENV APP	   ${GOPATH}/src/github.com/fission/fission/environments/go

WORKDIR ${APP}

ADD context	    ${APP}/context
ADD server.go   ${APP}

RUN go get
RUN go build -a -o /server server.go

ENTRYPOINT ["/server"]
EXPOSE 8888
