-include ../rules.mk

.PHONY: all
all: go-builder go-env-img go-env-1.14-img go-env-1.13-img go-env-1.12-img go-env-1.11.4-img

go-env-img: Dockerfile

go-env-1.14-img: Dockerfile-1.14

go-env-1.13-img: Dockerfile-1.13

go-env-1.12-img: Dockerfile-1.12

go-env-1.11.4-img: Dockerfile-1.11.4
