FROM kalilinux/kali-rolling

RUN apt-get update -y && apt-get install -y python3-pip python3-dev libev-dev 
RUN pip3 install --upgrade pip 
WORKDIR /app

COPY requirements.txt /app
RUN pip3 install -r requirements.txt

COPY . /app

ENTRYPOINT ["python3"]
CMD ["server.py"]