-include ../rules.mk

.PHONY: all
all: node-builder node-env-img node-env-debian-img node-env-12.16-img

node-env-img: Dockerfile

node-env-debian-img: Dockerfile-debian

node-env-12.16-img: Dockerfile-12.16
