ARG BUILDER_IMAGE=fission/builder
FROM ${BUILDER_IMAGE}
FROM kalilinux/kali-rolling:latest
RUN apt update && apt install -y curl

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -

RUN apt install -y nodejs

RUN curl -L https://www.npmjs.com/install.sh | sh

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

COPY --from=0 /builder /builder
ADD build.sh /usr/local/bin/build
RUN chmod +x /usr/local/bin/build
