ARG BUILDER_IMAGE=fission/builder
FROM ${BUILDER_IMAGE}
FROM node:lts

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

COPY --from=0 /builder /builder
ADD build.sh /usr/local/bin/build
RUN chmod +x /usr/local/bin/build
